#index:
   # path: /
  #  controller: App\Controller\DefaultController::index
terrain_index:
    path: /terrain/
    controller: App\Controller\TerrainController::index
# config/routes.yaml

app_event_index:
    path: /event/
    controller: 'App\Controller\EventController::index'
    methods: ['GET']

app_event_new:
    path: /event/new
    controller: 'App\Controller\EventController::new'
    methods: ['GET', 'POST']

app_event_show:
    path: /event/{id}
    controller: 'App\Controller\EventController::show'
    methods: ['GET']
    requirements:
        id: '\d+'

app_event_edit:
    path: /event/{id}/edit
    controller: 'App\Controller\EventController::edit'
    methods: ['GET', 'POST']
    requirements:
        id: '\d+'

app_event_delete:
    path: /event/{id}
    controller: 'App\Controller\EventController::delete'
    methods: ['POST']
    requirements:
        id: '\d+'
acceuil:
    path: '/front'
    controller: App\Controller\FrontController::home

app/event:
    path: '/front/event'
    controller: App\Controller\FrontController::event